Name: DeviceSettingsWidget
Type: FolderType
Children:
- Name: DeviceSettingsWidget
  Id: g=343e9a553a1648e3de95b91f6d877b43
  Supertype: Screen
  ReferenceType: HasComponent
  Children:
  - Name: HorizontalAlignment
    Type: BaseVariableType
    DataType: HorizontalAlignment
    ModellingRule: Optional
    Value: 3
  - Name: VerticalAlignment
    Type: BaseVariableType
    DataType: VerticalAlignment
    ModellingRule: Optional
    Value: 0
  - Name: Width
    Type: BaseVariableType
    DataType: Size
    ModellingRule: Optional
    Value: 700.0
  - Name: Height
    Type: BaseVariableType
    DataType: Size
    ModellingRule: Optional
    Value: 450.0
  - Name: NavigationPanel1
    Type: NavigationPanel
    Children:
    - Name: Panels
      Type: BaseObjectType
      Children:
      - Name: PLC
        Type: NavigationPanelItem
        Children:
        - Name: Title
          Type: BaseDataVariableType
          DataType: LocalizedText
          Value: {"LocaleId":"en-US","Text":"PLC"}
        - Name: Panel
          Type: NodePointer
          DataType: NodeId
          Value: "/Objects/HMI_6490_V13_0_00_OptxCom0/UI/___Main/Popup/DeviceSettingsWidget/DeviceSettingsWidgetComponents/Plc"
          Children:
          - Name: Kind
            Type: PropertyType
            DataType: NodeId
            Value: "/Types/ObjectTypes/BaseObjectType/BaseUIObject/Item/Container"
      - Name: HMI
        Type: NavigationPanelItem
        Children:
        - Name: Title
          Type: BaseDataVariableType
          DataType: LocalizedText
          Value: {"LocaleId":"en-US","Text":"HMI"}
        - Name: Panel
          Type: NodePointer
          DataType: NodeId
          Value: "/Objects/HMI_6490_V13_0_00_OptxCom0/UI/___Main/Popup/DeviceSettingsWidget/DeviceSettingsWidgetComponents/Hmi"
          Children:
          - Name: Kind
            Type: PropertyType
            DataType: NodeId
            Value: {"Id":71,"Namespace":6}
        - Name: AliasNode
          Type: BaseDataVariableType
          DataType: NodeId
          ValueRank: ScalarOrOneDimension
          Value: {"IdType":0,"Id":0,"Namespace":-1}
          Children:
          - Name: DynamicLink
            Type: DynamicLink
            DataType: NodePath
            Value: "../../../../SystemNode@NodeId"
      - Name: Diagnosis
        Type: NavigationPanelItem
        Children:
        - Name: Title
          Type: BaseDataVariableType
          DataType: LocalizedText
          Value: {"LocaleId":"en-US","Text":"HMI Diagnostics"}
        - Name: Panel
          Type: NodePointer
          DataType: NodeId
          Value: "/Objects/HMI_6490_V13_0_00_OptxCom0/UI/___Main/Popup/DeviceSettingsWidget/DeviceSettingsWidgetComponents/Diagnostics"
          Children:
          - Name: Kind
            Type: PropertyType
            DataType: NodeId
            Value: {"Id":71,"Namespace":6}
        - Name: AliasNode
          Type: BaseDataVariableType
          DataType: NodeId
          ValueRank: ScalarOrOneDimension
          Value: {"IdType":0,"Id":0,"Namespace":-1}
          Children:
          - Name: DynamicLink
            Type: DynamicLink
            DataType: NodePath
            Value: "../../../../SystemNode@NodeId"
      - Name: Panel1
        Type: NavigationPanelItem
        Children:
        - Name: Title
          Type: BaseDataVariableType
          DataType: LocalizedText
          Value: {"NamespaceIndex":-1,"LocaleId":"","Text":""}
        - Name: Panel
          Type: NodePointer
          DataType: NodeId
          Value: "/Objects/HMI_6490_V13_0_00_OptxCom0/UI/___Main/Popup/DeviceSettingsWidget/DeviceSettingsWidgetComponents/DateTimeSetUP"
          Children:
          - Name: Kind
            Type: PropertyType
            DataType: NodeId
            Value: "/Types/ObjectTypes/BaseObjectType/BaseUIObject/Item/Container"
        - Name: AliasNode
          Type: BaseDataVariableType
          DataType: NodeId
          ValueRank: ScalarOrOneDimension
          Value: {"IdType":0,"Id":0,"Namespace":-1}
          Children:
          - Name: DynamicLink
            Type: DynamicLink
            DataType: NodePath
            Value: "../../../../SystemNode@NodeId"
    - Name: CurrentPanel
      Type: NodePointer
      DataType: NodeId
      AccessLevel: Read
      Value: {"IdType":0,"Id":0,"Namespace":-1}
      Children:
      - Name: Kind
        Type: PropertyType
        DataType: NodeId
        Value: {"Id":6,"Namespace":6}
    - Name: Width
      Type: BaseVariableType
      DataType: Size
      ModellingRule: Optional
      Value: -1.0
    - Name: Height
      Type: BaseVariableType
      DataType: Size
      ModellingRule: Optional
      Value: 450.0
    - Name: HorizontalAlignment
      Type: BaseVariableType
      DataType: HorizontalAlignment
      ModellingRule: Optional
      Value: 3
    - Name: VerticalAlignment
      Type: BaseVariableType
      DataType: VerticalAlignment
      ModellingRule: Optional
      Value: 0
    - Name: TopMargin
      Type: BaseVariableType
      DataType: Size
      ModellingRule: Optional
      Value: 0.0
    - Name: BottomMargin
      Type: BaseVariableType
      DataType: Size
      ModellingRule: Optional
      Value: 0.0
    - Name: CurrentTabIndex
      Type: BaseDataVariableType
      DataType: Int32
      Value: 0
    - Class: Reference
      Target: ns=5;i=1181
    - Class: Reference
      Target: ns=5;i=1183
    - Name: TabHeight
      Type: BaseDataVariableType
      DataType: Size
      ModellingRule: Optional
      Value: 50.0
  - Name: SystemNode
    Type: NodePointer
    DataType: NodeId
    Value: "/Objects/HMI_6490_V13_0_00_OptxCom0/System/System"
    Children:
    - Name: Kind
      Type: PropertyType
      DataType: NodeId
      Value: "/Types/ObjectTypes/BaseObjectType/System"
  - Name: DeviceSettingsWidgetLogic
    Type: NetLogic
- File: DeviceSettingsWidgetComponents/DeviceSettingsWidgetComponents.yaml
